# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelHistory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelHistory

    pod 'Firebase/Messaging'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/CoreOnly'
    pod 'Alamofire', '~> 4.5'
    pod 'SwiftyJSON'

  target 'TravelHistoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelHistoryUITests' do
    # Pods for testing
  end

end
